version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wp-content:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - wordpress
    networks:
        - dockerNetwork
    restart: always

  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wordpress
    volumes:
      - ./wp-content:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_REDIS_HOST', 'redis' );
        define( 'WP_REDIS_PORT', '6379' );
    depends_on:
      - mysql
      - redis
    command: bash -c "pecl install redis ;docker-php-ext-enable redis ;docker-entrypoint.sh php-fpm"
    networks:
        - dockerNetwork
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'
    networks:
        - dockerNetwork
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
        - dockerNetwork
    restart: always
networks:
  dockerNetwork:
    name: dockerNetwork
    driver: bridge
